#----------------------------------------
# source zshenv
#----------------------------------------

source ~/dotfiles/config/zsh/env/customize.zsh

#----------------------------------------
# local settings
#----------------------------------------
# 固有の設定を追加するときは
# ~/.zshenv.local ファイルを作成し
# その中に記述すること
local_settings=~/.zshenv.local
if [ -e $local_settings ]; then
    source $local_settings
fi
