# TODO : plugin 対応

# Customize to your needs...
[ -f $HOME/dotfiles/config/zsh/rc/customize.zsh ] && source $HOME/dotfiles/config/zsh/rc/customize.zsh

#----------------------------------------
# local settings
#----------------------------------------
# 固有の設定を追加するときは
# ~/.zshrc.local ファイルを作成し
# その中に記述すること
local_settings=~/.zshrc.local
if [ -e $local_settings ]; then
    source $local_settings
fi
